"""Project and assessment synthesis.

The catalogue ships courses, not projects — but a learning path made only of
courses teaches recognition, not capability. Each phase therefore gets a
synthesised **project** whose deliverables are derived from the actual tools and
skills the phase's courses teach, plus **assessments** at the two points where
they change a decision:

* a *placement check* in phase 1, but only when the planner waived lower tiers on
  the strength of the learner's self-reported level. It is the cheapest way to
  falsify that assumption before it costs weeks.
* a *final evaluation* after the last phase, scoped to the skills the plan
  claimed it would deliver.

Nothing here is generated by a language model. Deliverables come from the phase's
own ``tools_covered`` and ``skills_taught`` values, and the artifact noun comes
from a keyword table over track names, so a Structural Analysis phase asks for a
load analysis report and a Web Development phase asks for a deployed app. That
keeps the output specific and reproducible with no API key.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

from app.ml.catalog import Catalog
from app.ml.intent import GoalInterpretation

if TYPE_CHECKING:  # avoids a circular import at module load
    from app.ml.planner import LearningPlan, PlanItem

#: Sort hints within a phase: assessment first, then courses (1), then the project.
_HINT_PLACEMENT = 0
_HINT_PROJECT = 2
_HINT_FINAL = 3

#: Effort for a synthesised project, by difficulty tier.
PROJECT_HOURS: dict[int, float] = {0: 6.0, 1: 12.0, 2: 20.0, 3: 35.0}

#: Project framing per tier.
PROJECT_KIND: dict[int, tuple[str, str]] = {
    0: ("Guided exercise set", "Practise the fundamentals until they are automatic"),
    1: ("Mini project", "Assemble the core skills into one small working result"),
    2: ("Applied project", "Solve a realistic, open-ended problem end to end"),
    3: ("Capstone project", "Deliver one substantial result that evidences the whole path"),
}

#: Track-name keyword -> (deliverable noun, three concrete deliverables).
#: First match wins, so more specific keywords are listed first.
ARTIFACT_RULES: tuple[tuple[tuple[str, ...], str, tuple[str, str, str]], ...] = (
    (
        ("computer vision", "medical imaging", "image"),
        "vision pipeline",
        ("An annotated dataset and preprocessing script",
         "A trained model with precision/recall reported per class",
         "A short failure analysis on the ten worst predictions"),
    ),
    (
        ("natural language", "language processing"),
        "language pipeline",
        ("A cleaned, tokenised corpus with documented preprocessing",
         "A working model with a held-out evaluation table",
         "Ten example inputs and outputs with commentary"),
    ),
    (
        ("machine learning", "artificial intelligence", "big data", "analytics", "healthcare data"),
        "model and evaluation report",
        ("A reproducible training script with a fixed random seed",
         "A metrics table against a documented baseline",
         "A one-page write-up of what the model gets wrong and why"),
    ),
    (
        ("web development", "software engineering"),
        "deployed web application",
        ("A running application with a public or local URL",
         "A README covering setup, architecture and trade-offs",
         "Automated tests covering the main user flow"),
    ),
    (
        ("mobile app",),
        "installable mobile app",
        ("A build that installs on a real device or emulator",
         "Screens for the primary user journey",
         "Notes on offline behaviour and error states"),
    ),
    (
        ("cybersecurity", "cyber"),
        "security assessment",
        ("A scoped assessment plan with explicit authorisation boundaries",
         "Findings ranked by severity with reproduction steps",
         "Remediation recommendations mapped to each finding"),
    ),
    (
        ("devops", "cloud computing"),
        "automated deployment pipeline",
        ("Infrastructure defined as code and version controlled",
         "A pipeline that builds, tests and deploys on commit",
         "Dashboards or logs proving a rollback works"),
    ),
    (
        ("blockchain",),
        "deployed contract and client",
        ("A contract deployed to a test network",
         "A test suite covering the failure paths",
         "A gas-cost and security review of the final version"),
    ),
    (
        ("database", "data structures", "algorithms", "operating systems", "computer networks"),
        "implementation and benchmark",
        ("A working implementation from first principles",
         "A benchmark comparing it against a library baseline",
         "A complexity analysis matching the measured curve"),
    ),
    (
        ("vlsi", "fpga", "semiconductor", "circuit", "microprocessor", "embedded", "iot"),
        "hardware design",
        ("A schematic or HDL source that simulates cleanly",
         "A timing and resource-utilisation report",
         "A test bench covering the specified corner cases"),
    ),
    (
        ("autonomous vehicle", "unmanned aerial", "robotics", "mechatronics", "industrial automation"),
        "working control system",
        ("A simulated or physical system that completes the task",
         "Sensor and control logs from at least three runs",
         "A tuning log explaining each parameter change"),
    ),
    (
        ("electric vehicle", "battery", "energy storage", "power system", "smart grid",
         "renewable", "power electronics", "high voltage", "electrical machine"),
        "system design and analysis",
        ("A sized design with all assumptions stated",
         "Load-flow or performance calculations against requirements",
         "A safety and efficiency review of the final design"),
    ),
    (
        ("structural", "bridge", "concrete", "earthquake", "geotechnical", "highway",
         "construction", "surveying", "building information"),
        "engineering design report",
        ("A dimensioned design meeting the governing code",
         "Load cases and analysis results with sample calculations",
         "A drawing set or model plus a bill of quantities"),
    ),
    (
        ("aerodynamics", "aircraft", "spacecraft", "satellite", "rocket", "propulsion",
         "orbital", "avionics", "space mission"),
        "design and simulation study",
        ("A parametric design with the governing equations shown",
         "Simulation results validated against a known case",
         "A trade study comparing at least three configurations"),
    ),
    (
        ("thermodynamics", "heat transfer", "fluid", "computational fluid", "turbomachinery",
         "hvac", "engine", "vibration", "finite element", "cad", "manufacturing", "additive"),
        "analysis and design package",
        ("A CAD or analysis model with meshing and boundary conditions documented",
         "Results compared against an analytical or published solution",
         "A design iteration log showing what improved and why"),
    ),
    (
        ("process control", "reaction", "refinery", "petrochemical", "polymer", "drilling",
         "reservoir", "well logging", "pipeline", "offshore"),
        "process design study",
        ("A process flow diagram with a full mass and energy balance",
         "Equipment sizing with the design basis stated",
         "A hazard and operability review of the final scheme"),
    ),
    (
        ("environment", "water treatment", "wastewater", "air pollution", "waste",
         "climate", "sustainab", "carbon capture", "gis"),
        "impact and mitigation study",
        ("A baseline assessment built from real measurements or public data",
         "A quantified mitigation design with costs",
         "A monitoring plan with defined thresholds and actions"),
    ),
    (
        ("medical device", "prosthetics", "biomechanics", "tissue", "biosensor",
         "bioinformatics", "neural engineering"),
        "device or analysis prototype",
        ("A prototype or analysis pipeline against a stated clinical need",
         "Verification results traced to each requirement",
         "A risk analysis covering the failure modes"),
    ),
    (
        ("six sigma", "lean", "supply chain", "operations research", "quality",
         "project management", "industry 4.0"),
        "improvement case study",
        ("A baseline measurement of the current process",
         "An intervention with the analysis that justified it",
         "Post-change results with a statistical significance check"),
    ),
)

#: Fallback when no keyword matches.
_DEFAULT_ARTIFACT = (
    "working prototype",
    ("A prototype demonstrating the phase's core skills",
     "Evidence that it meets a stated requirement",
     "A short write-up of the approach and its limitations"),
)


def synthesize_phase_items(
    plan: "LearningPlan",
    cat: Catalog,
    goal: GoalInterpretation,
    chosen: list[tuple[str, tuple[str, str], float]],
    waivers: list[dict] | None = None,
) -> None:
    """Append a project per phase, plus placement and final assessments.

    Mutates ``plan.items`` in place; the planner renumbers and schedules after.
    ``waivers`` is passed in rather than read from ``plan.analysis`` because the
    planner fills that in only once scheduling is done.
    """
    from app.ml.planner import PlanItem  # local import: planner imports this module

    if not plan.phases:
        return

    primary_track = chosen[0][0] if chosen else (goal.ranked_tracks[0][0] if goal.ranked_tracks else "")
    goal_label = _goal_label(goal, primary_track)

    for phase in plan.phases:
        courses = [i for i in plan.items if i.phase_index == phase.index and i.item_type == "course"]
        if not courses:
            continue

        tier = int(min(c.meta.get("tier", phase.index) for c in courses))
        track = _phase_track(courses, primary_track)
        tools = _unique(t for c in courses for t in _tools_of(cat, c.course_id))[:5]
        skills = _unique(s for c in courses for s in c.skills)[:6]

        kind, intent = PROJECT_KIND.get(tier, PROJECT_KIND[1])
        artifact, deliverables = _artifact_for(track)

        plan.items.append(
            PlanItem(
                item_type="project",
                title=f"{kind}: {artifact} for {goal_label}",
                hours=PROJECT_HOURS.get(tier, 12.0),
                phase_index=phase.index,
                phase_name=phase.name,
                origin="project",
                sort_hint=_HINT_PROJECT,
                skills=skills,
                rationale=(
                    f"{intent}. Courses teach recognition; building "
                    f"{'a' if artifact[0] not in 'aeiou' else 'an'} {artifact} is what "
                    f"proves you can apply {', '.join(skills[:3]) or 'these skills'}."
                ),
                meta={
                    "kind": kind,
                    "artifact": artifact,
                    "deliverables": list(deliverables),
                    "tools": tools,
                    "track": track,
                    "tier": tier,
                    "evaluation": _evaluation_criteria(skills),
                },
            )
        )

    # ---- placement check: only if the planner waived tiers ----
    if waivers:
        skipped = _unique(f"{w['track']} ({w['difficulty']})" for w in waivers)
        first = plan.phases[0]
        plan.items.append(
            PlanItem(
                item_type="assessment",
                title="Placement check: confirm the fundamentals we skipped",
                hours=1.5,
                phase_index=first.index,
                phase_name=first.name,
                origin="assessment",
                sort_hint=_HINT_PLACEMENT,
                skills=_phase_skills(plan, first.index)[:6],
                rationale=(
                    "Your path starts above the entry level because of how you described "
                    "your experience. This check falsifies that assumption in 90 minutes "
                    "instead of three weeks. Score below 70% and we will add the skipped "
                    f"material back: {', '.join(skipped[:3])}."
                ),
                meta={
                    "kind": "Placement check",
                    "pass_threshold": 0.7,
                    "waived": waivers,
                    "on_fail": "Re-plan with the skipped tiers restored.",
                },
            )
        )

    # ---- final evaluation over everything the plan promised ----
    last = plan.phases[-1]
    promised = _unique(
        s for i in plan.items if i.item_type == "course" for s in i.skills
    )[:10]
    plan.items.append(
        PlanItem(
            item_type="assessment",
            title=f"Final evaluation: {goal_label} readiness",
            hours=2.0,
            phase_index=last.index,
            phase_name=last.name,
            origin="assessment",
            sort_hint=_HINT_FINAL,
            skills=promised,
            rationale=(
                "Checks the specific competencies this path set out to build, so "
                "'finished' means demonstrated rather than merely watched."
            ),
            meta={
                "kind": "Final evaluation",
                "pass_threshold": 0.75,
                "covers_skills": promised,
                "sections": _evaluation_criteria(promised),
            },
        )
    )


# --------------------------------------------------------------------------- #
def _artifact_for(track: str) -> tuple[str, tuple[str, str, str]]:
    lowered = (track or "").lower()
    for keywords, artifact, deliverables in ARTIFACT_RULES:
        if any(k in lowered for k in keywords):
            return artifact, deliverables
    return _DEFAULT_ARTIFACT


def _goal_label(goal: GoalInterpretation, primary_track: str) -> str:
    """A short human label for what the learner is aiming at."""
    if goal.careers:
        return goal.careers[0].title()
    return primary_track or "your goal"


def _phase_track(courses: list["PlanItem"], primary_track: str) -> str:
    """The track a phase's project should be framed around.

    Uses the phase's *ladder* courses only. A gap top-up is a supporting course
    that happens to sort first, and letting it choose the artifact once framed a
    data-science phase as "build a deployment pipeline".
    """
    ladder = [c for c in courses if c.origin in ("ladder", "prerequisite")]
    for candidate in (ladder, courses):
        counts: dict[str, int] = {}
        for course in candidate:
            track = course.meta.get("track")
            if track:
                counts[track] = counts.get(track, 0) + 1
        if counts:
            if primary_track in counts:
                return primary_track  # the goal's strongest ladder wins ties
            return max(counts.items(), key=lambda kv: kv[1])[0]
    return primary_track


def _tools_of(cat: Catalog, course_id: str | None) -> list[str]:
    if not course_id:
        return []
    pos = cat.pos(course_id)
    return list(cat.df.iloc[pos]["tools_covered"]) if pos is not None else []


def _phase_skills(plan: "LearningPlan", phase_index: int) -> list[str]:
    """Skills taught by the courses of one phase, read from items directly."""
    return _unique(
        s
        for i in plan.items
        if i.phase_index == phase_index and i.item_type == "course"
        for s in i.skills
    )


def _evaluation_criteria(skills: list[str]) -> list[str]:
    """Turn skills into checkable criteria rather than vague objectives."""
    criteria = [f"Demonstrates {s} on a task you have not seen before" for s in skills[:4]]
    criteria.append("Work is reproducible from the artefacts alone")
    criteria.append("Limitations and next steps are stated explicitly")
    return criteria


def _unique(values) -> list[str]:
    seen: dict[str, None] = {}
    for v in values:
        seen.setdefault(v, None)
    return list(seen)
